# Numpy (Numerical Python)

Es uno de los paquetes fundamentales, en python para hacer cómputo científico, algunas de sus caracteristicas son:


* Tipo de datos Array.
* Funciones sofisticadas.
* Herramientas para integración de código.
* Modulo de Álgebra Lineal.
* Transformadas de Fourier.
* Números aleatorios.

## Uso de numpy

Para utilizar numpy utilizamos un alias:


In [211]:
import numpy as np # Importamos numpy, para su utilización 

## Array 

Es un tipo de datos, proporcionado por numpy que tiene por objeto el uso de:

* Vectores.
* Matrices.

Incluye además herramientas para manipular a estos objetos.

## Definición de vectores con numpy. 


Puede llevarse mediante la función array, que tiene por objeto el casting de un tipo de dato **list** a un tipo de datos **array**. 

### Caracteristicas 

Entre las principales caracteristicas del tipo array, tenemos:

1. Se definen con un tipo único de datos.
2. Son de tamaño estático.


In [15]:
# Construcción de un vector 3D
v = np.array([1.0,2.0,3.0])
print(v)

[1. 2. 3.]


In [16]:
# Se pueden acceder a cada elemento del arreglo, usando indices
print(v[0])
v[0] = 32.54
print(v)

1.0
[32.54  2.    3.  ]


In [62]:
y = np.array([1,2,0.3])
y.dtype

dtype('float64')

In [55]:
# Se pueden crear los arreglos, especificamente que dato contendra
w = np.array([1.0,2.0,3.0],dtype=float)
w.dtype # Especifica el tipo de dato que contiene en arreglo

dtype('float64')

In [57]:
w = np.array([1.0,2.0,3.0],dtype=complex)
w

array([1.+0.j, 2.+0.j, 3.+0.j])

In [63]:
a = np.array([1,2,3])   # Conversión silenciosa 
a[0] = 0.5
print(a)
a.dtype

[0 2 3]


dtype('int64')

In [64]:
a = a.astype(float)
a[0] = 0.5
print(a)
a.dtype

[0.5 2.  3. ]


dtype('float64')

## Operaciones entre vectores. 

Todas las operaciones básicas se llevan elemento a elemento.

In [5]:
# Definimos dos vectores distintos
v1 = np.array([2.3,3.1,9.6])
v2 = np.array([3.4,5.6,7.8])
print(v1)
print(v2)

[2.3 3.1 9.6]
[3.4 5.6 7.8]


In [6]:
# Operaciones entre vectores
(1/3)*v1 # Escalar por vector

array([0.76666667, 1.03333333, 3.2       ])

In [7]:
v1+v2 # Suma de vectores

array([ 5.7,  8.7, 17.4])

In [8]:
v1-v2 # Resta de vectores

array([-1.1, -2.5,  1.8])

In [9]:
v1*v2 # Multiplicación elemento a elemento

array([ 7.82, 17.36, 74.88])

In [10]:
v1/v2 # División elemento a elemento

array([0.67647059, 0.55357143, 1.23076923])

## Definición de Matrices. 


Las matrices se pueden crear de forma similar a los vectores usando listas, por medio de la funcón **mat** o mediante la función **matrix**:

In [47]:
# Matriz identidad de orden 3
A = np.matrix('1,0,0;0,1,0;0,0,1')
print(A)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
A.ndim  # Número de dimensiones de un arreglo 1: vector, 2: Matriz

2

In [124]:
np.ndim(A) # Número de dimensiones de un arreglo 1: vector, 2: Matriz

2

In [46]:
A.size  # Indica el número de elementos del arreglo

9

In [125]:
np.size(A) # Indica el número de elementos del arreglo

9

In [48]:
A.shape # Dimensiones de la matriz

(3, 3)

In [127]:
np.shape(A) # Dimensiones de la matriz

(3, 3)

In [51]:
len(A)  # Tamaño de la primera dimensión

3

In [52]:
1 in A  # El elemento se encuentra en el arreglo

True

In [53]:
32 in A # Verifica que el elemento se encuentre en el arreglo

False

In [32]:
# Matriz cuadrada 3x3
B = np.mat('3,1,3;2,1,1.5;1.3,0.2,1')
print(B)

[[3.  1.  3. ]
 [2.  1.  1.5]
 [1.3 0.2 1. ]]


In [43]:
# Matriz renglon
C = np.matrix([[1,2,3]])
print(C)

[[1 2 3]]


In [34]:
print(A[0,0])  # El acceso a cada elemento de una matriz, se hace por medio de dos indices.
A[0,1] = 2     # Modificamos el contenido de una matriz
print(A)

1
[[1 2 0]
 [0 1 0]
 [0 0 1]]


## Operaciones entre matrices


Las operaciones entre matrices se hacen elemento a elemento.

In [35]:
# Operaciones entre matrices
print(A+B) # Suma elemento a elemento

[[4.  3.  3. ]
 [2.  2.  1.5]
 [1.3 0.2 2. ]]


In [36]:
print(A-B) # Resta elemento a elemento

[[-2.   1.  -3. ]
 [-2.   0.  -1.5]
 [-1.3 -0.2  0. ]]


In [37]:
print(A*B) # Multiplicación elemento a elemento

[[7.  3.  6. ]
 [2.  1.  1.5]
 [1.3 0.2 1. ]]


In [38]:
A/B # División elemento a elemento

matrix([[0.33333333, 2.        , 0.        ],
        [0.        , 1.        , 0.        ],
        [0.        , 0.        , 1.        ]])

## Funciones básicas para la construcción de arreglos. 

Numpy, trae consigo una serie de funciones previamente construida, que pueden ser ocupadas con el fin de crear arreglos de forma simple. 

In [22]:
a = np.arange(10) # Genera una vector de 10 elementos de 0 a 9
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
b = np.arange(0,5,0.5) # Genera un vector de 10 elementos de 0 a 4.5
print(b)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5]


In [24]:
c = np.linspace(0,5,5) # Genera un vector de 4 elementos
print(c)

[ 0.    1.25  2.5   3.75  5.  ]


In [26]:
d = np.zeros(10)  # Genera un vector con 10 ceros
print(d)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [27]:
e = np.zeros((3,2)) # Genera una matriz con 6 ceros
print(e)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [71]:
f = np.ones(10)  # Genera un vector con 10 unos
print(f)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [72]:
g = np.ones((3,2)) # Genera una matriz con 6 unos
print(g)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [74]:
np.zeros_like(f)  # Genera un vector del mismo tamaño que otro, pero lleno de ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.zeros_like(g)   # Genera un vector del mismo tamaño que otro, pero lleno de ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [79]:
I = np.eye(3)     # Generamos una matriz identidad
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [83]:
np.diag(np.eye(5))

array([1., 1., 1., 1., 1.])

## Cambio de dimensión

Numpy permite cambiar las dimensiones de un arreglo, usando la función **reshape** o con la función **flatten**.


In [68]:
np.arange(100).reshape(10,10)l

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
np.ones((3,2)).flatten() 

array([1., 1., 1., 1., 1., 1.])

In [45]:
v = np.arange(10)
print(v)

[0 1 2 3 4 5 6 7 8 9]


## Rebanadas (Slicing) 

De la misma manera que en las listas podemos acceder a los elemntos de un arreglo, por medio de rebanadas. En el slicing de una lista se crea por defecto un nuevo objeto y en este caso se trabaja sobre el mismo arreglo. Además con esta tecnica es posible alterar los arreglos directamente. 

In [107]:
v = np.arange(10) # Generamos un vector de 10 elementos
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
v[:]     # Accedemos a todo el contenido del arreglo
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
v[2:5] # Accedemos el elemento con indice 2 hasta el 4

array([2, 3, 4])

In [104]:
v[2:5] = 100 # Modificamos el contenido de una parte 
v

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

In [109]:
v[:9:2]

array([0, 2, 4, 6, 8])

In [112]:
M = np.eye(10)
M

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [116]:
M[1,:]  # Accede a todos los elementos del segundo renglon

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [117]:
M[:,4]  # Accede a todos los elementos de la cuarta columna

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [119]:
M[2:4,:] # Accede a los renglones 2 y 3 del arreglo

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [120]:
M[2:4,1:4]

array([[0., 1., 0.],
       [0., 0., 1.]])

### Ejericicio.  Definir una matriz cuadrada de dimensión 10 llenas de ceros y otra matriz de tamaño 8 llena de unos, inserta la matriz de 8 en la de 10.

In [123]:
Z = np.zeros((10,10))  # Definimos una matriz llena de ceros
O = np.ones((8,8))     # Definimos una matriz llena de unos
Z[1:9,1:9] = O
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Operaciones de Álgebra Lineal  


Numpy trae consigo un gran número de funciones que pueden ser usadas en numpy.


In [134]:
A = np.linspace(1,9,9).reshape(3,3)
B = np.linspace(1,9,9).reshape(3,3)

In [135]:
A.T   # Transpuesta de la matriz

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [136]:
print(np.dot(A,B))  # Producto matriz-matriz

[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [139]:
print(A@B)          # Producto matriz-matriz

[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [140]:
print(np.dot(A,v1)) # Producto matriz-vector

[ 37.3  82.3 127.3]


In [142]:
print(A@v1)         # Producto matriz-vector

[ 37.3  82.3 127.3]


In [31]:
print(np.dot(v1,v2)) # Producto punto

100.06


In [143]:
print(v1@v2)         # Producto punto

100.06


# linalg Numpy

Numpy trae consigo un módulo para realizar otra clase de operaciones de álgebra lineal, como:

* Cálculo de la matriz inversa.
* Cálculo de determinantes.
* Cálculo de eigen-valores.
* Solución de sistemas de ecuaciones lineales.

In [146]:
D = np.array([[3,2,1],[0,2,-5],[-2,1,4]])  # Definimos una matriz

In [148]:
np.linalg.det(D)    # Calculo del determinante de una matriz

62.99999999999999

In [213]:
np.trace(A) # Traza de una matriz

4

In [150]:
eigenValores, eigenVectores = np.linalg.eig(D) # Calculo de eigen-valores y eigen-vectores

In [151]:
print(eigenValores)

[4.88452998+0.        j 2.05773501+2.94339769j 2.05773501-2.94339769j]


In [152]:
print(eigenVectores)

[[-0.54739866+0.        j -0.28166702-0.41379711j -0.28166702+0.41379711j]
 [-0.72489181+0.        j  0.74599422+0.        j  0.74599422-0.        j]
 [ 0.41819443+0.        j -0.008614  -0.43915153j -0.008614  +0.43915153j]]


In [154]:
np.linalg.inv(D)   # Cálculo de la matriz inversa

array([[ 0.20634921, -0.11111111, -0.19047619],
       [ 0.15873016,  0.22222222,  0.23809524],
       [ 0.06349206, -0.11111111,  0.0952381 ]])

In [157]:
D@np.linalg.inv(D)  # Multiplicación de la matriz por su inversa

array([[ 1.00000000e+00,  0.00000000e+00,  1.38777878e-17],
       [ 5.55111512e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [159]:
# Definimos el sistema de ecuaciones lineales
A = np.array([[2,3,1],[1,2,1],[-1,4,0]]) # Definimos la matriz A
b = np.array([3,1,2])    # Vector b
x = np.linalg.solve(A,b)  # Vector solución
x

array([ 1.2,  0.8, -1.8])

In [161]:
A@x - b  # Comprobación de la solución del sistema de ecuaciones

array([4.4408921e-16, 0.0000000e+00, 0.0000000e+00])

In [215]:
np.linalg.norm(b) # Norma euclidiana de un vector

3.7416573867739413

In [220]:
np.linalg.norm(b,np.inf) # Norma infinita de un vector

3.0

In [222]:
np.linalg.norm(A,np.inf) # Norma infinita de una matriz

6.0

# Notación Índice

Se puede utilizar el convenio de Einsten para realizar operaciones en numpy.

In [226]:
np.einsum('ii',A)  # Traza de la matriz usando la convención de einsten

4

In [227]:
np.einsum('ij, jk', A, A)  # Producto matricial

array([[ 6, 16,  5],
       [ 3, 11,  3],
       [ 2,  5,  3]])

In [228]:
A@A

array([[ 6, 16,  5],
       [ 3, 11,  3],
       [ 2,  5,  3]])

In [229]:
 np.einsum('ij, j', A, b)  # Matriz por vector

array([11,  7,  1])

In [230]:
A@b

array([11,  7,  1])

In [231]:
np.einsum('i, i', b, b)  # Producto escalar por sí mismo

array(14)

# Números pseudoaleatorios en numpy.

No hay algoritmos que generen números aleatorios. Con la computadora generamos números pseudoaleatorios, en Python se utiliza un algoritmo llamado **Mersenne twister**.

En numpy se generan por medio del paquete **random**.

In [163]:
np.random.rand()  # Devuelve un número entre 0 y 1.

0.6580612384626829

In [166]:
np.random.rand(5)  # Devuelve un arreglo de 5 elementos pseudoaletorios

array([0.72789621, 0.74149823, 0.29454969, 0.54483063, 0.88066564])

In [168]:
np.random.rand(3,2)  # Devuelve una matriz de numeros aletorios entre cero y 1

array([[0.21979764, 0.34283786],
       [0.57688532, 0.55393497],
       [0.66869312, 0.44713459]])

A veces necesitamos usar una secuencia pseudoaletoria, en ese caso podemos utilizar una semilla(condición inicial), por defecto siempre la semilla es la hora, de la computadora.

In [176]:
np.random.seed(0)  # Establecemos una semilla 

In [177]:
np.random.rand()

0.5488135039273248

In [178]:
np.random.rand(3,3)

array([[0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152]])

In [179]:
np.random.seed(0)  # Establecemos una semilla 

In [180]:
np.random.rand()

0.5488135039273248

In [181]:
np.random.rand(3,3)

array([[0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152]])

In [191]:
np.random.randint(10) # Un número aleatorio entero que no pase de 10

9

In [193]:
np.random.randint(6,8) # Número aleatorio entre 6 y 8

7

In [196]:
np.random.randint(10,20,5)  # Arreglos aleatorios entre 10 y 20, de tamaño 5

array([13, 13, 13, 17, 10])

In [198]:
np.random.randint(10,20,(3,3))  # Arreglos aleatorios entre 10 y 20, de tamaño 3x3

array([[12, 10, 10],
       [14, 15, 15],
       [16, 18, 14]])

In [200]:
arreglo = np.arange(100)  # Generamos un arreglo propio

In [206]:
np.random.choice(arreglo) # Tomamos de manera pseudoaletorio el número

58

In [207]:
np.random.choice(arreglo,3) # Tomamos de manera pseudoaletorio el número

array([31,  1, 65])

In [209]:
np.random.choice(arreglo,(3,3)) # Tomamos de manera pseudoaletorio el número

array([[91,  0, 14],
       [99, 53, 12],
       [42, 84, 75]])

In [210]:
np.random.choice(arreglo,300) # Tomamos de manera pseudoaletorio el número

array([68,  6, 68, 47,  3, 76, 52, 78, 15, 20, 99, 58, 23, 79, 13, 85, 48,
       49, 69, 41, 35, 64, 95, 69, 94,  0, 50, 36, 34, 48, 93,  3, 98, 42,
       77, 21, 73,  0, 10, 43, 58, 23, 59,  2, 98, 62, 35, 94, 67, 82, 46,
       99, 20, 81, 50, 27, 14, 41, 58, 65, 36, 10, 86, 43, 11,  2, 51, 80,
       32, 54,  0, 38, 19, 46, 42, 56, 60, 77, 30, 24,  2,  3, 94, 98, 13,
       40, 72, 19, 95, 72, 26, 66, 52, 67, 61, 14, 96,  4, 67, 11, 86, 77,
       75, 56, 16, 24, 29, 21, 25, 80, 60, 61, 83, 33, 32, 70, 85, 31, 13,
       71, 56, 24, 79, 41, 18, 40, 54, 79, 11, 38, 93,  1, 95, 44, 88, 24,
       67, 82,  3, 76, 35, 86, 61, 69, 87, 43, 32, 11, 84, 10, 54, 37, 28,
        2, 27, 83, 89, 23, 53, 51, 46, 20, 53, 29, 67, 35, 39,  9, 73, 41,
       23,  3, 46, 90, 50,  3, 31,  9, 10, 27, 45, 71, 39, 61, 85, 97, 44,
       34, 34, 88, 33,  5, 36,  0, 75, 34, 69, 53, 80, 62,  8, 61,  1, 81,
       35, 91, 40, 36, 48, 25, 67, 35, 30, 29, 33, 18, 17, 93, 84,  2, 69,
       12, 44, 66, 91, 85

## Funciones Matemáticas

Numpy, trae consigo una serie de funciones matemáticas previamente constridas, estas pueden ser aplicadas a los arreglos. 

In [35]:
x = np.linspace(0,2*np.pi)  # numpy define sus propias constantes como pi
print(x)

[ 0.          0.12822827  0.25645654  0.38468481  0.51291309  0.64114136
  0.76936963  0.8975979   1.02582617  1.15405444  1.28228272  1.41051099
  1.53873926  1.66696753  1.7951958   1.92342407  2.05165235  2.17988062
  2.30810889  2.43633716  2.56456543  2.6927937   2.82102197  2.94925025
  3.07747852  3.20570679  3.33393506  3.46216333  3.5903916   3.71861988
  3.84684815  3.97507642  4.10330469  4.23153296  4.35976123  4.48798951
  4.61621778  4.74444605  4.87267432  5.00090259  5.12913086  5.25735913
  5.38558741  5.51381568  5.64204395  5.77027222  5.89850049  6.02672876
  6.15495704  6.28318531]


In [36]:
np.sin(x)

array([  0.00000000e+00,   1.27877162e-01,   2.53654584e-01,
         3.75267005e-01,   4.90717552e-01,   5.98110530e-01,
         6.95682551e-01,   7.81831482e-01,   8.55142763e-01,
         9.14412623e-01,   9.58667853e-01,   9.87181783e-01,
         9.99486216e-01,   9.95379113e-01,   9.74927912e-01,
         9.38468422e-01,   8.86599306e-01,   8.20172255e-01,
         7.40277997e-01,   6.48228395e-01,   5.45534901e-01,
         4.33883739e-01,   3.15108218e-01,   1.91158629e-01,
         6.40702200e-02,  -6.40702200e-02,  -1.91158629e-01,
        -3.15108218e-01,  -4.33883739e-01,  -5.45534901e-01,
        -6.48228395e-01,  -7.40277997e-01,  -8.20172255e-01,
        -8.86599306e-01,  -9.38468422e-01,  -9.74927912e-01,
        -9.95379113e-01,  -9.99486216e-01,  -9.87181783e-01,
        -9.58667853e-01,  -9.14412623e-01,  -8.55142763e-01,
        -7.81831482e-01,  -6.95682551e-01,  -5.98110530e-01,
        -4.90717552e-01,  -3.75267005e-01,  -2.53654584e-01,
        -1.27877162e-01,

In [37]:
np.cos(x)

array([ 1.        ,  0.99179001,  0.96729486,  0.92691676,  0.8713187 ,
        0.80141362,  0.71834935,  0.6234898 ,  0.51839257,  0.40478334,
        0.28452759,  0.1595999 ,  0.03205158, -0.09602303, -0.22252093,
       -0.34536505, -0.46253829, -0.57211666, -0.67230089, -0.76144596,
       -0.8380881 , -0.90096887, -0.94905575, -0.98155916, -0.99794539,
       -0.99794539, -0.98155916, -0.94905575, -0.90096887, -0.8380881 ,
       -0.76144596, -0.67230089, -0.57211666, -0.46253829, -0.34536505,
       -0.22252093, -0.09602303,  0.03205158,  0.1595999 ,  0.28452759,
        0.40478334,  0.51839257,  0.6234898 ,  0.71834935,  0.80141362,
        0.8713187 ,  0.92691676,  0.96729486,  0.99179001,  1.        ])

In [38]:
np.tan(x)

array([  0.00000000e+00,   1.28935722e-01,   2.62230881e-01,
         4.04855131e-01,   5.63189508e-01,   7.46319396e-01,
         9.68445994e-01,   1.25396034e+00,   1.64960460e+00,
         2.25901742e+00,   3.36933183e+00,   6.18535359e+00,
         3.11836824e+01,  -1.03660461e+01,  -4.38128627e+00,
        -2.71732305e+00,  -1.91681278e+00,  -1.43357520e+00,
        -1.10111114e+00,  -8.51312412e-01,  -6.50927865e-01,
        -4.81574619e-01,  -3.32022875e-01,  -1.94749983e-01,
        -6.42021301e-02,   6.42021301e-02,   1.94749983e-01,
         3.32022875e-01,   4.81574619e-01,   6.50927865e-01,
         8.51312412e-01,   1.10111114e+00,   1.43357520e+00,
         1.91681278e+00,   2.71732305e+00,   4.38128627e+00,
         1.03660461e+01,  -3.11836824e+01,  -6.18535359e+00,
        -3.36933183e+00,  -2.25901742e+00,  -1.64960460e+00,
        -1.25396034e+00,  -9.68445994e-01,  -7.46319396e-01,
        -5.63189508e-01,  -4.04855131e-01,  -2.62230881e-01,
        -1.28935722e-01,