# Evaluación de formulas

Normalmente se requieren programas que evaluen una formula matemática, para una gran cantidad de datos. La manera más común de hacerlo es definir una función que contenga la formula y con ayuda de ciclos ir evaluando para cada dato.

In [4]:
import numpy as np

In [5]:
print("Fuerza: %f"%(1*3)) # Podemos usar a python, simplemente como una calculadora

Fuerza: 3.000000


In [6]:
masa = 1
aceleracion = 3
fuerza1 = masa*aceleracion
print("Fuerza %.2f"%(fuerza1))

Fuerza 3.00


In [7]:
from math import sinh, exp, e, pi
x = 2*pi
r1 = sinh(x)
r2 = 0.5*(exp(x) - exp(-x))
r3 = 0.5*(e**x - e**(-x))
print ('%.16f %.16f %.16f' % (r1,r2,r3))

267.7448940410164369 267.7448940410164369 267.7448940410163232


In [8]:
def fuerzaN(m,a):
    return m*a

In [9]:
masa        = np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0])
aceleracion = np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0])

In [10]:
fuerza = np.zeros(len(masa))
for i in range(len(masa)):
    fuerza[i] = fuerzaN(masa[i],aceleracion[i])
fuerza

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [11]:
fuerza2 = fuerzaN(masa,aceleracion)
fuerza2

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [12]:
masa        = [1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
aceleracion = [1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
fuerza3 = fuerzaN(masa,aceleracion)

TypeError: can't multiply sequence by non-int of type 'list'

## numpy.vectorize()

Ayuda a que funciones que sólo aceptan un escalar, puedan aceptar listas. Esta función es parecido a usar **map**. 

In [13]:
fuerza4 = np.vectorize(fuerzaN)

In [16]:
print(type(masa))
print(type(aceleracion))
fuerza3 = fuerza4(masa,aceleracion)

<class 'list'>
<class 'list'>


In [17]:
fuerza3

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])